### ISSUE TITLE
pictures inside marginfigure chunk

### ISSUE THREAD

**Issue by rpietro** [eddelbuettel/tint#11]
I love tint, just started using it for a wide variety of documents. However, when I try to insert a figure inside a marginfigure, the html output gets shifted to the right far beyond the remaining margin content. I know the advice is to keep the margingfigure content as simple as possible, but does that necessarily include not adding figures?

My code:

````
{marginfigure}
![](bulldog.jpg)
```
`
The output:

![screenshot from 2016-10-09 17-05-57](https://cloud.githubusercontent.com/assets/693031/19223653/09983254-8e43-11e6-8fbc-4637e6c7b71e.png)

**Comment by eddelbuettel** [comment]
Two or three quick thoughts:

1. Try the tufte package for comparison. That may be structural.
2. Don't use markdown graphics. They barely have sizing, let alone placement.
3. Stick with basics. Copy the latex-alike / knitr fragments you see. 

That "worked for me".  I think what you do here it outside of the "unwritten" spec.

**Comment by eddelbuettel** [comment]
Closing this now.
