### ISSUE TITLE
Knitting in pdf fail

### ISSUE THREAD

**Issue by Trowic** [eddelbuettel/tint#12]
Hello,

I wanted to use the pdf output format from tint and i cant't figure why pdflatex is failing to generate the pdf.
I tried the default template from the tint 0.0.2 package and hitted the knit button in rstudio (same thing happen when i use rmarkdown::render() ) and got this output :

```
/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS tint_test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output tint_test.pdf --template /usr/local/lib/R/site-library/tint/rmarkdown/templates/pdf/resources/tintPdf-template.tex --highlight-style pygments --latex-engine pdflatex --variable 'documentclass:tufte-handout' --bibliography skeleton.bib --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc 
output file: tint_test.knit.md

! Undefined control sequence.
\maketitle ...p \thispagestyle {plain}\tuftebreak 
                                                  \@afterindentfalse \@after...
l.165 \maketitle

pandoc: Error producing PDF from TeX source
Erreur : pandoc document conversion failed with error 43
Exécution arrêtée
```

The tufte version works (but has horrible font :p ).

**Comment by eddelbuettel** [comment]
Well it clearly works for me and others. It will be a dependency issue.  

Strange that tufte works.  Can you add `keep_tex: TRUE` and run `pdflatex` on the .tex for debugging? Ie make the header

```yaml
output:
  tint::tintPdf: 
    keep_tex: TRUE
```

As I said, "works for me" on Ubuntu.  What is your system?

**Comment by Trowic** [comment]
It fails before it can produce the .tex file.

My system is debian so it should work ...
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=fr_FR.UTF8       LC_NUMERIC=C              LC_TIME=fr_FR.UTF8        LC_COLLATE=fr_FR.UTF8     LC_MONETARY=fr_FR.UTF8   
 [6] LC_MESSAGES=fr_FR.UTF8    LC_PAPER=fr_FR.UTF8       LC_NAME=C                 LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=fr_FR.UTF8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1 yaml_2.1.13 knitr_1.14 
```

The yaml header of my file is this : 
```
---
title: "Tint Is Not Tufte"
subtitle: "An implementation in R Markdown"
author: "JJ Allaire, Yihui Xie, Dirk Eddelbuettel"
date: "`r Sys.Date()`"
output:
  tint::tintPdf:
    keep_tex: TRUE
bibliography: skeleton.bib
link-citations: yes
---
```

And if i replace `tint::tintPdf:` by `tufte::tufte_handout:` it works (generate the `.tex` and `.pdf` files).

I modified the pandoc command that prints in the console `/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS tint_test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output tint_test.pdf --template /usr/local/lib/R/site-library/tint/rmarkdown/templates/pdf/resources/tintPdf-template.tex --highlight-style pygments --latex-engine pdflatex --variable 'documentclass:tufte-handout' --bibliography skeleton.bib --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc` and replace `--output tint_test.pdf` by `--output tint_test.tex` then i have the .tex file but pdflatex give me the same bug : 

```
! Undefined control sequence.
\maketitle ...p \thispagestyle {plain}\tuftebreak
                                                  \@afterindentfalse \@after...
l.165 \maketitle

```
And here the .tex [https://gist.github.com/Trowic/a400b03621c63fa50c0db6a251fa5c63](https://gist.github.com/Trowic/a400b03621c63fa50c0db6a251fa5c63)

**Comment by eddelbuettel** [comment]
We will get to this as I can setup similar Debian setups.  But let us hone in a little more:

- What version of texlive, ie `dpkg -S /usr/share/texlive/texmf-dist/tex/latex/tufte-latex/tufte-handout.cls` points the texlive-pictures package, on my workstation I have `2015.20160320-1`
- Your analysis is IMHO wrong. The error you show _is_ from (la)tex processing.
- We need a more detailed log of what (latex) packages get loaded etc pp
- Just to be sure: you don't have any other texlive installations or version of tufte-handout, correct?

**Comment by eddelbuettel** [comment]
I just fired up a Docker instance of the Rocker variant [hadleyverse](https://github.com/rocker-org/hadleyverse/blob/master/Dockerfile) as this already contains a good chunk of texlive.  After installing two more packages ( texlive-generic-recommended, texlive-fonts-extra) I was able to process skeleton.Rmd without issues.

**Comment by Trowic** [comment]
Here is the output :
```
 dpkg -S /usr/share/texlive/texmf-dist/tex/latex/
tufte-latex/tufte-handout.cls
texlive-pictures: /usr/share/texlive/texmf-dist/tex/latex/tufte-latex/tufte-handout.cls
```
And the texlive-pictures version is `texlive-pictures/stable,now 2014.20141024-2 all`

I didn't meant the \tuftebreak was the issue, I get it that it's a latex processing issue, I was just pointing out what command causes the bug.

I have no other texlive installation, juste the one from the debian packages, and only one tufte version also.

Here is the log if i force pdflatex to continue anyway : [test.log](https://gist.github.com/Trowic/a400b03621c63fa50c0db6a251fa5c63#file-test-log) [bug occurs here](https://gist.github.com/Trowic/a400b03621c63fa50c0db6a251fa5c63#file-test-log-L1141)

I tried to read it all but i can't find out why it stops.

**Comment by eddelbuettel** [comment]
Very strange. Older versions of texlive should not be the issue; tufte-handout is a pretty mature package.

But there is nothing more I can do to help you at this point. It appears to be your machine.

**Comment by Trowic** [comment]
It appears so.
Thank you very much for your help and this package.

**Comment by eddelbuettel** [comment]
Ok, I'll close this.

**Comment by Trowic** [comment]
Just for the record, downloading the latest tufte-latex.zip from the github repo (should work with the CTAN version) and manually installing it according to [this comment](http://tex.stackexchange.com/a/39165) solved my issue.

Thanks again for the `tint` package :)

**Comment by eddelbuettel** [comment]
Ok, glad you have it working.   Just curious, though:  what is your platform? 

I am on Ubuntu / Debian and never had issue with the provided texlive.  I added a short section with the list of packages I use.

**Comment by Trowic** [comment]
My sessionInfo is :
```r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)
```
From what i understand of the docker file you used, it downloads packages from the unstable branch for Debian ([see here](https://github.com/rocker-org/hadleyverse/blob/master/Dockerfile#L7:L17)).

The version of the [texlive-pictures](https://packages.debian.org/jessie/texlive-pictures) package in debian stable seems rather old, but there was only [one](https://github.com/Tufte-LaTeX/tufte-latex/blob/master/History.txt#L1) minor change in the tufte-latex package in the meantime. 

I'll my beg my IT team to get me a brand new VM :D

**Comment by jpolonsky** [comment]
I'm not sure whether to open a new issue or not, but I have the same failure, and have located the source. In the .tex file that results from knitting the template in RStudio, on line 160 there is the line `\tuftebreak% add some space before the text begins`. If I comment this out, the doc complies fine, but fails if that is left in. Do you have any thoughts why that might be - is there a way to not have that line in the template? Thanks

**Comment by eddelbuettel** [comment]
Sorry, did you just edit something here?  Git just alerted me ...

**Comment by jpolonsky** [comment]
Apologies, I have the same error and thought I had found the source (the
line `\tuftebreak% add some space before the text begins`), before
realising this had already been mentioned above. It must be my machine -
I'll try a fresh install of Tex and see if that resolves the issue

**Comment by eddelbuettel** [comment]
Two of us just updated the package and used it extensively -- without issues.

What is your platform and/or texlive version?

**Comment by jpolonsky** [comment]
My texlive version is pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015) and session info is as below:

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1    tufte_0.4         htmltools_0.3.6   tools_3.5.1      
 [5] yaml_2.2.0        Rcpp_1.0.0        rmarkdown_1.10.15 tint_0.1.0       
 [9] knitr_1.20        digest_0.6.18     evaluate_0.12    
```

**Comment by eddelbuettel** [comment]
I see.  TeX Live 2015 is a little suspicious, you may have to pay that "tax" of not being able to use Tufte styles and tint.  I am in a similar situation at work under CentOS and a similarly old (or older) TeX Live.
Otherwise can't help with macOS.

Suggest the issue remain closed.  There is not problem on recent systems / systems with recent enough tex installations.  CRAN checks that diligently.

**Comment by jpolonsky** [comment]
Yes, I think it might be a little outdated. I'll install the latest texlive and report back how that goes. Thanks for your time

**Comment by jpolonsky** [comment]
Just to let you know I updated latex and the problem has been resolved
