### ISSUE TITLE
Roberto Condensed a fine sans-serif, but 

### ISSUE THREAD

**Issue by technocrat** [eddelbuettel/tint#14]
an option to select a serif font is essential for any application that will have large text blocks. Especially if the hardwired font is so heavy on the page. Also, the text runs off the bottom of the page sometimes.

Like the overall simplification, tho'

**Comment by eddelbuettel** [comment]
Soory but that won't happen -- if you want to use a Serif font just use e.g. the [tufte package](https://cran.r-project.org/package=tufte).
