### ISSUE TITLE
Make tint compatible with rmarkdown pages

### ISSUE THREAD

**Issue by mwillumz** [eddelbuettel/tint#21]
I'd like to see tint made compatible with rmarkdown pages and their floating TOC, website header, and other features. I wonder if this would be possible? I'm willing to work on this myself but thought I'd check to see if it's already being considered (or whether there are any known major hurdles).

**Comment by eddelbuettel** [comment]
To a first approximation, tint does what the tufte class does.  Does its html variant do it?

**Comment by mwillumz** [comment]
Understood... and no I don't believe it does. I'll post over on tufte's repo.
