### ISSUE TITLE
Side references in pdf

### ISSUE THREAD

**Issue by javilol** [eddelbuettel/tint#22]
I know it is not implemented in tufte, but I would like to use side references in PDF output as it is in HTML.

Is it at all possible?

I know this is a feature request and not an issue, and I am not even sure this is the place to make a request. If it is not, I will close it right away, just notify me.

**Comment by eddelbuettel** [comment]
I fear this is something we need to close -- I did not do any restyling beside removing the background color, and adjusting fonts.  "Re-working" Tufte is a much bigger project and probably not right for tint.
