### ISSUE TITLE
Book version or  bookdown support?

### ISSUE THREAD

**Issue by lf-araujo** [eddelbuettel/tint#24]
Tint is awesome, thanks for the package.

Is there a way of printing a tufte-book version of tint? Better yet, is there support for bookdown?

Thank you,

**Comment by eddelbuettel** [comment]
This is a modified version of the [tufte package](https://cloud.r-project.org/web/packages/tufte/index.html) offering "Tufte-style" _handouts_ in pdf and html, and the documentation says so quite clearly.  

If you need/want _book_ support, someone would need to add it.  Idem for bookdown support.

**Comment by eddelbuettel** [comment]
And don't get me wrong, I'd like that too.  But I am not even aware of a decent starting point and a decent Tufte book class.

**Comment by lf-araujo** [comment]
Thanks @eddelbuettel , I will try to port it to bookdown in February for a book I am writing. Will report back here if successful.

Best.

**Comment by eddelbuettel** [comment]
I eventually needed that too, and now have _some_ support in the master branch.  I used with `rmarkdown::render()` and `bookdown::render_book("index.Rmd")` (given suitable other files).

**Comment by eddelbuettel** [comment]
And that is now on CRAN in [version 0.1.0](http://dirk.eddelbuettel.com/blog/2018/04/08#tint_0.1.0).
