### ISSUE TITLE
Path to skeleton.bib

### ISSUE THREAD

**Issue by dmenne** [eddelbuettel/tint#27]
When I build the template example of tint (Date: 2018-04-08) under Windows and tinytex/texlive, I get 

```
I couldn't open database file skeleton.bib.bib
---line 121 of file aaa.aux
 : \bibdata{skeleton.bib
 :  
```
Solution:  Use `bibliography: ./skeleton.bib` in YAML

**Comment by eddelbuettel** [comment]
Could that be a local issue for you as winbuilder or CRAN never reported anything?   On a project I currently work I put the bibliography file into a subdirectory includes/ so I have 

```
bibliography: includes/references.bib
```

there. You could try that too.

**Comment by dmenne** [comment]
Retried with default template. Problem without leading `./` only occurs with Pdf and Book. HTML works with and without `./`, giving inline references, but no end-of-file references.
Same symptoms when I put in a subdirectory. i.e. `./includes/skeleton.bib` vs. includes/skeleton.bib

**Comment by eddelbuettel** [comment]
Html does not use the latex / pdf tool chain. It seems to be bibtex with its variant of kpathsearch.

Methinks you want to open an issue with tinytex and close this here.  There is no issue in tint.
