### ISSUE TITLE
\@ref(fig:name) within tintBook 

### ISSUE THREAD

**Issue by ssp3nc3r** [eddelbuettel/tint#33]
I really like the tintBook setup so far. 

It would be great to add the ability to reference tables and figures using the book down syntax \\@ref(\<type\>:\<name\>) — where \<type\> is something like fig or tab, and \<name\> is the R code chunk name — within tintBook.

**Comment by eddelbuettel** [comment]
Should just work if you drop the @ and use curlies -- we use LaTeX after all.

**Comment by ssp3nc3r** [comment]
Yes, thanks!
