### ISSUE TITLE
Subtitle not working if the output is pdf

### ISSUE THREAD

**Issue by claudiofronterre** [eddelbuettel/tint#34]
Hello,

I noticed that the subtitle is not show if the output is pdf. I tried it with the template provided when I open a new tint pdf rmarkdown document. Is this a known issue?

Thank you,

Claudio

**Comment by eddelbuettel** [comment]
I _think_ it is a "on-purpose" _feature_ of the Tufte style.  You could try the tufte style and see if it has a subtitle.  If that is the case we _could_ consider adding though the original idea really still holds: like tufte, but with updated fonts and without the yellow-ish background.

**Comment by eddelbuettel** [comment]
Closing as no follow-up and seen as 'defined behaviour' by style designer, _i.e._ Tufte.
