### ISSUE TITLE
Typo in README: mentions "release 0.2.0"

### ISSUE THREAD

**Issue by RaoOfPhysics** [eddelbuettel/tint#35]
Hi @eddelbuettel. The README mentions "release 0.2.0" under [PDF Font Variants](https://github.com/eddelbuettel/tint/blob/master/README.md#pdf-font-variants) &ndash; introduced on [22 November 2018](https://github.com/eddelbuettel/tint/commit/71955e862e59f89ca14d42f7254130b6778e6c20#diff-04c6e90faac2675aa89e2176d2eec7d8); I'm guessing this is a typo? Should it say 0.1.1?

Also, I noticed that the CRAN badge hasn't updated to show `v0.1.1` and I wonder if this is something you can trigger on your end.

Thanks for the nice package!

**Comment by eddelbuettel** [comment]
Whoops. At some point @jonathan-g and I thought the next one would be called 0.2.0, but it implied some additional features we didn't get to yet so 0.1.1 follow 0.1.0.  I'll fix the README.md. 

I don't understand the issue with the badge though.  That is redirected by the service. I'll poke 
@gaborcsardi -- for other recent packages of mine I get the current version but https://www.r-pkg.org/badges/version/tint is stuck at the previous, 0.1.0, and not 0.1.1.

**Comment by eddelbuettel** [comment]
Thanks to @gaborcsardi for fixing / updating the backend value.  The badge is now correct too.

**Comment by RaoOfPhysics** [comment]
Thanks for resolving this so quickly, @eddelbuettel and @gaborcsardi!
