### ISSUE TITLE
pdf header control

### ISSUE THREAD

**Issue by akuyper** [eddelbuettel/tint#38]
Is there a way to control header text on pdf handouts? 

Updated to new version 0.1.2 of `tint` and the pdf header is now lower case instead of small caps as in previous versions.

**Comment by eddelbuettel** [comment]
The release was five months ago...   

If there is something you found better in 0.1.1, maybe just stick with 0.1.1?  Else _everything_ is configurable it just depends on who has enough time to add options to support it.

**Comment by akuyper** [comment]
Understood. I will revert back to 0.1.1. 

Not 100% sure what I should be customizing here. I was digging around in `~/templates/tintPdf/resources/tintPdf-template.tex` file trying to figure out what I should be adjusting. A novice when it comes to this stuff so any suggestions or guidance on what file I should really be looking at would be greatly appreciated but not expected.

Please feel free to simple close the issue though.

Thank you.

**Comment by eddelbuettel** [comment]
This stuff is tricky.  But in general the flow something like
  - say yes / no in YAML header
  - pick that up as variable on the R processing call, here in `tint::tintPdf()` (I assume)
  - and then pickk that up in the `template.tex` to tickle behaviour from the style file

I just did all that for `watermark` in the sibbling package `pinp`.  Special case that I made it a document option.  Else maybe do some diggiing `diff` between 0.1.1 and 0.1.2 (or studdy the commits).  _If_ I changed something it may have been on purpose (hah!)   Otherwise quite a few changes came in 0.1.1 with all @jonathan-g added. 

As life is short though could always just make a local copy of the class file and use that or ...

**Comment by eddelbuettel** [comment]
And, lastly, for completeness:   _which_ documentation or demo file are you referring too?   Your initial report was a little short on that.

**Comment by akuyper** [comment]
Thanks for the guidance. I will poke around and see if I can figure it out. 

I was examining `tint/README.md` which contains screenshots of pdfs demonstrating how to select alternative fonts. You can see the right header on page 2 of each example is different. One does lowercase and the other does small caps. I tested to see if this had to do with changing the fonts by adding the appropriate info to the yaml, but that didn't make a difference.

I used the template provided when opening an rmarkdown file with RStudio - `This is not Tufte (PDF)`. This is what you are asking for right?

I just tried the `This is not Tufte (PDF, book)` template and it generate small caps for the headers.

**Comment by eddelbuettel** [comment]
The screenshots are of course one-offs and can be old.  Behaviour in a bug report would be most specific by saying something like "I rendered the source of the vignette" or "of doc file xts" or, as you did, "I let RStudio create a document" (but even there we now have two variants).

So are you saying what you wanted in the handout is in the bookformat?

**Comment by akuyper** [comment]
I've been rendering `tint/inst/rmarkdown/templates/tintPdf/skeleton/skeleton.Rmd`. 

Yes, the bookformat does what I want for the headers. Page 10 or 11 print headers using small caps in the upper left and right of the respective pages. Rendered `tint/inst/rmarkdown/templates/tintBook/skeleton/skeleton.Rmd`.

**Comment by akuyper** [comment]
Need to have the `microtype` latex package to ensure you will get small caps in header when building a `tintPDF`.
