### ISSUE TITLE
Is there a way to add vertical space between sidenotes

### ISSUE THREAD

**Issue by f0nzie** [eddelbuettel/tint#41]
Hello Dirk,
I am working on a PDF using `tint` using lots of margin notes for figures and text. This is the link to the `Rmd` file, if you are interested in seeing it.:  https://github.com/f0nzie/transcript_interview_john_hopfield_by_lex_fridman/blob/master/John_Hopfield-Physics_View_of_the_Mind_and_Neurobiology-AI_Podcast_76_with_Lex_Fridman-tint.Rmd 

What I noticed is that these sidenotes have a small vertical spacing between them. This is an example of one of the pages:

![image](https://user-images.githubusercontent.com/29108853/80625013-2b605780-8a12-11ea-993d-41a22bea5a6a.png)

I have been exploring ways to add more vertical space but I have not been successful even when adding a custom `.tex` template; I am able to modify the section titles but could not find a way to make changes to the sidenotes.

Any thoughts?

**Comment by eddelbuettel** [comment]
None. I haven't tweaked that -- spacing issues are tricky.

Maybe try CTAN or a latex experts forum?

**Comment by f0nzie** [comment]
Thanks.

**Comment by f0nzie** [comment]
I gave it another try using ideas from https://github.com/Tufte-LaTeX/tufte-latex/blob/master/sample-handout.tex. It turned out that I can mix and match any Latex code inside or outside the sidenotes. For instance, I can use `vspace` to add positive or negative spacing between figures or marging notes. It's pretty cool. Another thing I discovered is that I can make reference to the figures using `\ref{fig:name-of-the-figure-in-knitr}`. You can see the results here https://github.com/f0nzie/transcript_interview_john_hopfield_by_lex_fridman/blob/master/John_Hopfield-Physics_View_of_the_Mind_and_Neurobiology-AI_Podcast_76_with_Lex_Fridman-tint.pdf.

Thanks.

**Comment by eddelbuettel** [comment]
Yes, and yes.  True for all RMarkdown and LaTeX mixes.
