### ISSUE TITLE
cross references

### ISSUE THREAD

**Issue by ericpgreen** [eddelbuettel/tint#45]
I really like the look of `tint::tintHtml`. Is it possible to use cross references for figures and tables like in `?bookdown::tufte_html2` with `\@ref(fig:chunk_name)`?

**Comment by eddelbuettel** [comment]
I frankly do not know; I use pdf more.  I do not recall purposely _removing_ functionality.

Have you tried?  If you try (just replicating what `tufte` does), what happens?  If something 'bad' or unexpected happens, can you maybe try to chase it in the code?

**Comment by ericpgreen** [comment]
Thanks. Yes, I tried a few options. In both `tufte::tufte_html: default` and `tint::tintHtml`, the html just prints `@ref(fig:chunk_name)`.

It works with `bookdown::tufte_html2`.

Maybe the issue is that cross references are special to bookdown? ([source](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html)):

<img width="813" alt="Screen Shot 2020-12-29 at 4 22 53 PM" src="https://user-images.githubusercontent.com/546433/103314958-35e44e00-49f2-11eb-9da3-08bc82226208.png">

**Comment by eddelbuettel** [comment]
It is possible that we cannot support these within an `rmarkdown` document.  I do know (roughly) how LaTeX does it, and it happens after the R processing.   So _maybe_ we can get to this via `pandoc`; else you're stuck unitl someone codes this up, which most likely won't be me -- sorry!

**Comment by eddelbuettel** [comment]
Also: https://github.com/lierdakil/pandoc-crossref looks useful.  Maybe all this is doable via `lua` filters to `pandoc`.

But again, looks like no immediate free lunch to be had.  Sorry!

**Comment by ericpgreen** [comment]
No worries! I just wanted to make sure I was not missing something. I will either fiddle with `bookdown::tufte_html2` to get the appearance I want or fiddle with `tint::tintHtml` to get cross references. Thanks.

**Comment by eddelbuettel** [comment]
Keep me posted if you find something operational for `tint::tintHtml`.

**Comment by paessens** [comment]
cross-referencing with ***\ref{fig:label}*** works just fine if you compile a tint-pdf

output:
  tint::tintPdf:
    latex_engine: lualatex
    keep_tex:  false

**Comment by SteveRankine** [comment]
Hi, thanks for the nice package.
For html w/ cross-ref, [html_document2](https://bookdown.org/yihui/bookdown/a-single-document.html)  seems to work for me:
````
---
output:   
  bookdown::html_document2:
    base_format: tint::tintHtml
---
````

Happy knitting!
