### ISSUE TITLE
keep_tex: true not supported

### ISSUE THREAD

**Issue by alanchmiel** [eddelbuettel/tint#50]
There are instances where I would need to integrate this output into latex, and it would be valuable to have an option like

```
output: tint::tintPdf:
   keep_tex: true
```

However, it is not supported, and returns:

>Error in yaml::yaml.load(..., eval.expr = TRUE) : 
>  Scanner error: mapping values are not allowed in this context at line 5, column 22
>Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
>Execution halted

If a workaround exists, I can't figure it out.

**Comment by eddelbuettel** [comment]
Yes, I think I had wrestles that at times too but not enough to descent into the code.

You can approximate it easily enough by calling `render("myfile.Rmd", intermediates_dir="scrapheap")` which is what I just did on the `tintPDF.Rmd` and I promptly have `tintPDF.tex` therein.  Good enough?

**Comment by alanchmiel** [comment]
Good enough.

Thanks you.
